# Generated by Django 6.0.6 on 2026-06-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('facility_build', 'Facility build'), ('facility_upgrade', 'Facility upgrade'), ('sport_license', 'Sport license purchase'), ('bid_won', 'Free agent bid won'), ('wage_payment', 'Manager pays player wage'), ('club_deal_fee', 'Club pays manager monthly fee'), ('signing_bonus', 'Signing bonus'), ('medical_treatment', 'Medical treatment fee'), ('tournament_entry', 'Tournament entry fee'), ('tournament_prize', 'Tournament prize'), ('admin_grant', 'Admin grant/correction')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
