# Generated by Django 6.0.6 on 2026-07-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('facility_build', 'Facility build'), ('facility_upgrade', 'Facility upgrade'), ('construction', 'Facility construction project'), ('sport_license', 'Sport license purchase'), ('bid_won', 'Free agent bid won'), ('wage_payment', 'Manager pays player wage'), ('club_deal_fee', 'Club pays manager monthly fee'), ('signing_bonus', 'Signing bonus'), ('medical_treatment', 'Medical treatment fee'), ('tournament_entry', 'Tournament entry fee'), ('tournament_prize', 'Tournament prize'), ('admin_grant', 'Admin grant/correction')], max_length=30),
        ),
    ]
