# Generated by Django 6.0.6 on 2026-07-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('economy', '0002_alter_transaction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to='companies.company'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('facility_build', 'Facility build'), ('facility_upgrade', 'Facility upgrade'), ('construction', 'Facility construction project'), ('sport_license', 'Sport license purchase'), ('bid_won', 'Free agent bid won'), ('wage_payment', 'Manager pays player wage'), ('club_deal_fee', 'Club pays manager monthly fee'), ('signing_bonus', 'Signing bonus'), ('medical_treatment', 'Medical treatment fee'), ('tournament_entry', 'Tournament entry fee'), ('tournament_prize', 'Tournament prize'), ('admin_grant', 'Admin grant/correction'), ('company_founding', 'Company founding fee'), ('dividend', 'Company dividend payout'), ('npc_wage', 'Company pays NPC workforce wages')], max_length=30),
        ),
    ]
