# Generated by Django 6.0.6 on 2026-06-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('kc_balance', models.PositiveIntegerField(default=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('soccer_field', 'Soccer field'), ('sports_hall', 'Sports hall'), ('swimming_pool', 'Swimming pool'), ('tennis_court', 'Tennis court'), ('gym', 'Gym'), ('medical_center', 'Medical center')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='clubs.club')),
            ],
            options={
                'unique_together': {('club', 'facility_type')},
            },
        ),
        migrations.CreateModel(
            name='SportLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Football')], max_length=30)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_licenses', to='clubs.club')),
            ],
            options={
                'unique_together': {('club', 'sport')},
            },
        ),
    ]
