# Generated by Django 6.0.6 on 2026-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('stadium', 'Stadium'), ('sports_hall', 'Sports hall'), ('swimming_pool', 'Swimming pool'), ('tennis_court', 'Tennis court'), ('fight_gym', 'Fight gym'), ('gym', 'Gym'), ('medical_center', 'Medical center')], max_length=20),
        ),
        migrations.AlterField(
            model_name='season',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('futsal', 'Futsal'), ('handball', 'Handball'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('water_polo', 'Water polo'), ('marathon', 'Marathon'), ('sprint_100m', 'Sprint 100m'), ('sprint_400m', 'Sprint 400m'), ('swimming', 'Swimming'), ('tennis', 'Tennis'), ('table_tennis', 'Table tennis'), ('mma', 'MMA'), ('boxing', 'Boxing'), ('kickboxing', 'Kickboxing'), ('wrestling', 'Wrestling'), ('bjj', 'Brazilian jiu-jitsu'), ('judo', 'Judo'), ('powerlifting', 'Powerlifting'), ('weightlifting', 'Weightlifting'), ('bodybuilding', 'Bodybuilding'), ('crossfit', 'CrossFit')], default='football', max_length=30),
        ),
        migrations.AlterField(
            model_name='sportlicense',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('futsal', 'Futsal'), ('handball', 'Handball'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('water_polo', 'Water polo'), ('marathon', 'Marathon'), ('sprint_100m', 'Sprint 100m'), ('sprint_400m', 'Sprint 400m'), ('swimming', 'Swimming'), ('tennis', 'Tennis'), ('table_tennis', 'Table tennis'), ('mma', 'MMA'), ('boxing', 'Boxing'), ('kickboxing', 'Kickboxing'), ('wrestling', 'Wrestling'), ('bjj', 'Brazilian jiu-jitsu'), ('judo', 'Judo'), ('powerlifting', 'Powerlifting'), ('weightlifting', 'Weightlifting'), ('bodybuilding', 'Bodybuilding'), ('crossfit', 'CrossFit')], max_length=30),
        ),
    ]
