# Generated by Django 6.0.6 on 2026-07-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_rename_soccer_field_to_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.PositiveSmallIntegerField()),
                ('to_level', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=12)),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('cost_kc', models.PositiveIntegerField()),
                ('required_workers', models.PositiveIntegerField()),
                ('required_guards', models.PositiveIntegerField()),
                ('is_major', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_projects', to='clubs.facility')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'in_progress'))), fields=('facility',), name='one_active_project_per_facility')],
            },
        ),
        migrations.CreateModel(
            name='SeasonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'Football'), ('futsal', 'Futsal'), ('handball', 'Handball'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('water_polo', 'Water polo'), ('marathon', 'Marathon'), ('sprint_100m', 'Sprint 100m'), ('sprint_400m', 'Sprint 400m'), ('swimming', 'Swimming'), ('tennis', 'Tennis'), ('table_tennis', 'Table tennis'), ('mma', 'MMA'), ('boxing', 'Boxing'), ('kickboxing', 'Kickboxing'), ('wrestling', 'Wrestling'), ('bjj', 'Brazilian jiu-jitsu'), ('judo', 'Judo'), ('powerlifting', 'Powerlifting'), ('weightlifting', 'Weightlifting'), ('bodybuilding', 'Bodybuilding'), ('crossfit', 'CrossFit')], max_length=30)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_registrations', to='clubs.club')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.season')),
            ],
            options={
                'unique_together': {('club', 'season')},
            },
        ),
    ]
