# Generated by Django 6.0.6 on 2026-07-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_constructionproject_seasonregistration'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='construction_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='construction_contracts', to='companies.company'),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='construction_price_lc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='security_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_contracts', to='companies.company'),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='security_price_lc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='kc_balance',
            field=models.PositiveIntegerField(default=500000),
        ),
    ]
