# Generated by Django 6.0.6 on 2026-07-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_lipa_x100_and_season_names'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityStaffingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], max_length=12)),
                ('in_house', models.BooleanField(default=False)),
                ('monthly_price_lc', models.PositiveIntegerField()),
                ('active_from', models.DateTimeField(auto_now_add=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_contracts', to='clubs.facility')),
                ('provider_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staffing_contracts', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active_until__isnull', True)), fields=('facility', 'service_type'), name='one_active_contract_per_facility_service')],
            },
        ),
    ]
