"""Croatian (HR) name pools. (name, weight) — higher weight = more common."""

FIRST_NAMES = [
    ("Ivan", 10), ("Marko", 10), ("Luka", 10), ("Josip", 9), ("Ante", 9),
    ("Petar", 8), ("Tomislav", 8), ("Matej", 8), ("Karlo", 8), ("David", 8),
    ("Filip", 8), ("Jakov", 7), ("Mateo", 7), ("Fran", 7), ("Nikola", 7),
    ("Stjepan", 7), ("Andrija", 6), ("Domagoj", 6), ("Hrvoje", 6), ("Krešimir", 6),
    ("Mario", 6), ("Dario", 6), ("Igor", 6), ("Goran", 6), ("Zoran", 5),
    ("Davor", 5), ("Dragan", 5), ("Zvonimir", 5), ("Branimir", 5), ("Vedran", 5),
    ("Dino", 5), ("Bruno", 5), ("Leon", 5), ("Roko", 5), ("Niko", 5),
    ("Šime", 5), ("Duje", 5), ("Toni", 5), ("Lovro", 5), ("Borna", 5),
    ("Patrik", 4), ("Antonio", 4), ("Kristijan", 4), ("Danijel", 4), ("Matija", 4),
    ("Vjekoslav", 4), ("Miroslav", 4), ("Božidar", 4), ("Vlado", 4), ("Mislav", 4),
    ("Jerko", 4), ("Jure", 4), ("Frane", 4), ("Zlatko", 4), ("Željko", 4),
    ("Damir", 4), ("Nenad", 4), ("Predrag", 3), ("Saša", 3), ("Siniša", 3),
    ("Robert", 3), ("Denis", 3), ("Alen", 3), ("Sandro", 3), ("Marin", 3),
    ("Marijan", 3), ("Slaven", 3), ("Vatroslav", 3), ("Kruno", 3), ("Krunoslav", 3),
    ("Ognjen", 3), ("Ivor", 3), ("Vito", 3), ("Emanuel", 3), ("Gabrijel", 3),
    ("Rafael", 3), ("Noa", 3), ("Adrian", 3), ("Erik", 3), ("Viktor", 3),
    ("Teo", 3), ("Tin", 3), ("Vid", 3), ("Jan", 3), ("Ivano", 2),
    ("Silvio", 2), ("Renato", 2), ("Boris", 2), ("Milan", 2), ("Ratko", 2),
    ("Stipe", 2), ("Mladen", 2), ("Nikša", 2), ("Vinko", 2), ("Anđelko", 2),
    ("Ivica", 2), ("Tihomir", 2), ("Ozren", 2), ("Julijan", 2), ("Leopold", 1),
]

LAST_NAMES = [
    ("Horvat", 10), ("Kovačević", 9), ("Babić", 9), ("Marić", 8), ("Jurić", 8),
    ("Novak", 8), ("Kovačić", 8), ("Knežević", 7), ("Vuković", 7), ("Marković", 7),
    ("Petrović", 7), ("Matić", 7), ("Tomić", 7), ("Pavlović", 6), ("Kovač", 6),
    ("Božić", 6), ("Blažević", 6), ("Grgić", 6), ("Pavić", 6), ("Radić", 6),
    ("Perić", 6), ("Filipović", 6), ("Šarić", 6), ("Lovrić", 5), ("Vidović", 5),
    ("Perković", 5), ("Popović", 5), ("Bošnjak", 5), ("Jukić", 5), ("Barišić", 5),
    ("Čović", 5), ("Klarić", 5), ("Nikolić", 5), ("Ivanović", 5), ("Petković", 5),
    ("Matković", 5), ("Brkić", 5), ("Josipović", 4), ("Katić", 4), ("Marušić", 4),
    ("Galić", 4), ("Živković", 4), ("Cindrić", 4), ("Šimić", 4), ("Lukić", 4),
    ("Martinović", 4), ("Bilić", 4), ("Vrdoljak", 4), ("Bakarić", 4), ("Modrić", 4),
    ("Rakitić", 4), ("Mandžukić", 4), ("Perišić", 4), ("Brozović", 4), ("Kramarić", 4),
    ("Vlašić", 4), ("Livaković", 4), ("Gvardiol", 4), ("Šutalo", 4), ("Majer", 4),
    ("Pašalić", 4), ("Budimir", 4), ("Oršić", 4), ("Jelavić", 4), ("Kalinić", 4),
    ("Ćorluka", 3), ("Srna", 3), ("Pranjić", 3), ("Rebić", 3), ("Kovačev", 3),
    ("Šuker", 3), ("Bobek", 3), ("Cvitanović", 3), ("Zebec", 3), ("Boban", 3),
    ("Prosinečki", 3), ("Štimac", 3), ("Jarni", 3), ("Vlaović", 3), ("Stanić", 3),
    ("Tudor", 3), ("Šola", 3), ("Balaban", 3), ("Kranjčar", 3), ("Olić", 3),
    ("Klasnić", 3), ("Krpan", 3), ("Babić-Kos", 1), ("Sesar", 3), ("Bubalo", 3),
    ("Zorić", 3), ("Zekić", 3), ("Zelić", 3), ("Vučković", 3), ("Vuković-Novak", 1),
    ("Vukas", 3), ("Vranković", 3), ("Vojnović", 3), ("Vlahović", 3), ("Vitez", 3),
    ("Uremović", 3), ("Turk", 3), ("Tot", 3), ("Tokić", 3), ("Terzić", 3),
    ("Tadić", 3), ("Šoštarić", 3), ("Šokčević", 3), ("Škorić", 3), ("Škarica", 3),
    ("Sablić", 3), ("Rukavina", 3), ("Rubčić", 3), ("Rožić", 3), ("Rogić", 3),
    ("Ribarić", 3), ("Raos", 2), ("Rajković", 3), ("Radoš", 3), ("Puljić", 3),
    ("Prpić", 3), ("Prlić", 2), ("Pintarić", 3), ("Pezelj", 2), ("Pehar", 2),
    ("Pavletić", 3), ("Paviček", 2), ("Papić", 3), ("Palinić", 2), ("Padovan", 2),
    ("Ostojić", 3), ("Odak", 2), ("Obradović", 3), ("Nižetić", 2), ("Nimac", 2),
    ("Nemet", 2), ("Mužek", 2), ("Musulin", 2), ("Mrkonjić", 3), ("Modrušan", 2),
    ("Mlinarić", 3), ("Mišković", 3), ("Milardović", 2), ("Mihaljević", 3), ("Meštrović", 3),
    ("Medved", 3), ("Medić", 3), ("Matoš", 3), ("Matijašević", 3), ("Markotić", 2),
    ("Malenica", 2), ("Majstorović", 3), ("Magdić", 2), ("Lučić", 3), ("Lozić", 3),
    ("Lončar", 4), ("Leko", 3), ("Lauš", 2), ("Kuzmanić", 2), ("Kutleša", 2),
    ("Kušen", 2), ("Kurtović", 3), ("Kunac", 2), ("Kulaš", 2), ("Krznarić", 3),
    ("Krolo", 2), ("Krišto", 2), ("Kraljević", 3), ("Kraljić", 3), ("Kosor", 2),
    ("Kos", 3), ("Komadina", 2), ("Kolar", 3), ("Kojić", 2), ("Klobučar", 3),
    ("Kirin", 2), ("Kelava", 2), ("Karlović", 3), ("Karamatić", 2), ("Kapetanović", 3),
    ("Jusup", 2), ("Juranić", 2), ("Jozić", 3), ("Jelić", 3), ("Jelača", 2),
    ("Jazvić", 2), ("Janković", 3), ("Jakšić", 3), ("Ivić", 3), ("Ivančić", 3),
    ("Husnjak", 2), ("Hrgović", 3), ("Hrelja", 2), ("Herceg", 3), ("Hajduk", 2),
    ("Gudelj", 3), ("Grubišić", 3), ("Grbeša", 2), ("Golubić", 3), ("Gojak", 2),
    ("Glavina", 2), ("Gavran", 3), ("Gašparović", 3), ("Franić", 3), ("Fabijanić", 2),
    ("Erceg", 3), ("Dvornik", 2), ("Duvnjak", 3), ("Dujmović", 3), ("Držić", 2),
    ("Dragičević", 3), ("Dolenec", 2), ("Delić", 3), ("Ćurić", 3), ("Čupić", 2),
    ("Čizmić", 2), ("Čerina", 2), ("Cvitković", 3), ("Crnković", 3), ("Cikatić", 2),
    ("Bulat", 3), ("Bujas", 2), ("Budak", 3), ("Brekalo", 3), ("Bogdanović", 3),
    ("Bertović", 2), ("Benković", 3), ("Bekavac", 2), ("Bašić", 4), ("Bartulović", 3),
    ("Banić", 3), ("Bandić", 2), ("Baković", 3), ("Bagarić", 3), ("Antunović", 3),
]
