# Generated by Django 6.0.6 on 2026-07-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_quarter_to_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='kc_balance',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
