# Generated by Django 6.0.6 on 2026-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_lipa_x100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPopulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, unique=True)),
                ('retired', models.PositiveIntegerField(default=0)),
                ('youth_generated', models.PositiveIntegerField(default=0)),
                ('topped_up', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='HR', max_length=2),
        ),
    ]
