# Generated by Django 6.0.6 on 2026-07-08 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0005_constructionproject_seasonregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('company_type', models.CharField(choices=[('construction', 'Construction'), ('security', 'Security'), ('cleaning', 'Cleaning')], max_length=20)),
                ('kc_balance', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_as_ceo', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(choices=[('construction_worker', 'Construction worker'), ('security_guard', 'Security guard'), ('cleaner', 'Cleaner')], max_length=25)),
                ('monthly_wage_lc', models.PositiveIntegerField()),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company')),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='clubs.constructionproject')),
            ],
        ),
        migrations.CreateModel(
            name='ShareTransferOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_offers', to='companies.company')),
                ('from_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_offers_made', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_offers_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='companies.company')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'holder')},
            },
        ),
    ]
