# Generated by Django 6.0.6 on 2026-07-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_facilitystaffingcontract'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='clubs.facilitystaffingcontract'),
        ),
    ]
